[package]
name = "kohaku-merkle-tree"
version = "0.1.0"
edition = "2024"

[features]
default = []
parallel = ["dep:rayon"]

[dependencies]
rayon = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }

[[bench]]
name = "merkle"
harness = false
