[package]
name = "kohaku-userop-kit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[features]
default = ["bundler"]
bundler = []

[dependencies]
alloy = { workspace = true, features = [
    "signers",
    "dyn-abi",
    "rpc",
    "rpc-types",
] }
alloy-sol-types = { workspace = true, features = ["eip712-serde"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom_02 = { version = "0.2", package = "getrandom", features = ["js"] }
gloo-timers = { workspace = true, features = ["futures"] }

[build-dependencies]
cfg_aliases = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
