[package]
name = "kohaku-tornadocash"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[features]
default = ["paymaster", "remote-circuit", "bench"]
paymaster = ["dep:kohaku-userop-kit"]
parallel = ["websnark-rs/parallel"]
remote-circuit = []
bench = []

[dependencies]
alloy = { workspace = true, features = [
    "rpc",
    "rpc-types",
    "network",
    "providers",
    "transports",
    "sol-types",
    "reqwest",
] }
ark-bn254 = { workspace = true }
ark-ff = { workspace = true }
async-trait = { workspace = true }
brotli = { workspace = true }
hex = { workspace = true }
postcard = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
ruint = { workspace = true, features = ["ark-ff-06", "num-bigint"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
kohaku-userop-kit = { workspace = true, optional = true }
websnark-rs = { workspace = true }
tokio = { workspace = true, features = ["process", "rt-multi-thread"] }
num-bigint = { workspace = true }
num-traits = { workspace = true }
blake-hash = { workspace = true }
kohaku-merkle-tree = { workspace = true }
kohaku-kv-store = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = [
    "signers",
    "signer-local",
    "provider-anvil-node",
    "contract",
] }
anyhow = { workspace = true }
criterion = { workspace = true, features = ["async_tokio"] }
insta = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[bench]]
name = "merkle"
harness = false
required-features = ["bench"]

[[bench]]
name = "prove"
harness = false
required-features = ["bench"]

[build-dependencies]
cfg_aliases = { workspace = true }

[lints]
workspace = true
