[package]
name = "kohaku-frametx-kit"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
alloy = { workspace = true, features = [
    "signers",
    "signer-local",
    "rpc",
    "rpc-types",
] }
anyhow = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = ["signers", "signer-local"] }

[lints]
workspace = true
