[package]
name = "kohaku-tornadocash-keychain"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
kohaku-tornadocash = { workspace = true }
ruint = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
alloy = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
