[package]
name = "kohaku-eip-1193"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["wasm-bindgen-futures"]

[lib]
crate-type = ["rlib"]

[features]
default = ["alloy"]
alloy = ["alloy/network", "alloy/providers"]
js = [
    "dep:tsify",
    "dep:js-sys",
    "dep:serde-wasm-bindgen",
    "dep:wasm-bindgen",
    "dep:wasm-bindgen-futures",
    ]

[dependencies]
alloy = { workspace = true, features = ["rpc", "rpc-types", "sol-types"] }
async-trait = { workspace = true }
hex = { workspace = true }
js-sys = { workspace = true, optional = true }
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true, optional = true }
thiserror = { workspace = true }
tsify = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }
wasm-bindgen-futures = { workspace = true, optional = true }
web-time = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { workspace = true, features = ["futures"] }

[build-dependencies]
cfg_aliases = { workspace = true }

[lints]
workspace = true
