[package]
name = "kohaku-crypto"
version = "0.1.0"
edition = "2024"

[features]
parallel = ["dep:rayon"]

[dependencies]
ark-bn254 = { workspace = true }
rayon = { workspace = true, optional = true }
ark-ff = { workspace = true }
blake-hash = { workspace = true }
num-bigint = "0.4.6"
num-traits = { workspace = true }
poseidon-rust = { workspace = true }
ruint = { workspace = true, features = ["ark-ff-06", "serde"] }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tracing-test = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "pedersen"
harness = false

[[bench]]
name = "babyjubjub"
harness = false

[lints]
workspace = true
