name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: nix-community/cache-nix-action@v7
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "packages/crates"

    - run: nix develop .#ci
    - run: nix develop .#ci --command bash -c "cd crates && cargo clippy"
    - run: nix develop .#ci --command bash -c "cd crates && cargo test --release"
    - run: nix develop .#ci --command bash -c "cd crates && cargo test --release -- --ignored"
